nacos:
  config:
    server-addr: 182.92.202.68:8015
    namespace: bf100dae-330c-4fce-a783-d63aecac842b

server:
  port: 8002

spring:
  application:
    name: nacos-springboot-config-mysql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update